version: '3.8'

services:
  db-notification:
    container_name: database-notification
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - notification-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-alpine
    volumes:
      - /var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - notification-network

  notification-service:
    container_name: notification-service
    build: .
    environment:
      PORT_HTTP: ${PORT_HTTP}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db-notification
      POSTGRES_PORT: ${POSTGRES_PORT}
      RABBITMQ_HOST: rabbitmq
    ports:
      - 3002:3002
    depends_on:
      - db-notification
      - rabbitmq
    volumes:
      - .:/home/notification-service
    networks:
      - notification-network

networks:
  notification-network:
