version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-alpine
    volumes:
      - /var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - notification-network

  notification-service:
    container_name: notification-service
    build: .
    environment:
      PORT_HTTP: ${PORT_HTTP}
      RABBITMQ_HOST: rabbitmq
    ports:
      - 3002:3002
    depends_on:
      - rabbitmq
    volumes:
      - .:/home/notification-service
    networks:
      - notification-network

networks:
  notification-network:
